# List of LXD VM/container hostnames to deploy to.
# One per line. Lines starting with # are comments.
# Example:
# dev-ross
# dev-matt
# dev-alice
copytrading
dev-bolik
dev-claude
dev-dave
dev-lesik
dev-matt
dev-mich
dev-resla
dev-ross
dev-steve