apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram-arb-alerts
        type: telegram
        settings:
          bottoken: "8674250017:AAEEkQJR54zaqdpFxXQ-QVEgGZijErhuuPY"
          chatid: "-5158636501"

policies:
  - orgId: 1
    receiver: Telegram
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
