apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: DS_LOKI
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Tempo
    type: tempo
    uid: DS_TEMPO
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: DS_LOKI
        tags:
          - key: developer.name
          - key: service.instance.id
          - key: run.id
      serviceMap:
        datasourceUid: DS_PROMETHEUS
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: DS_LOKI

  - name: Monitoring-Clickhouse
    type: grafana-clickhouse-datasource
    uid: DS_MONITORING_CLICKHOUSE
    access: proxy
    url: http://10.77.251.87:9000  # Changed to the HTTP port
    editable: true
    jsonData:
      server: 10.77.251.87
      port: 8123
      defaultDatabase: default
      username: default 
      secureJsonData:
        password: "default"
