apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: DS_LOKI
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Monitoring-Clickhouse
    type: grafana-clickhouse-datasource
    uid: DS_MONITORING_CLICKHOUSE
    access: proxy
    url: http://10.77.251.87:9000  # Changed to the HTTP port
    editable: true
    jsonData:
      server: 10.77.251.87
      port: 8123
      defaultDatabase: default
      username: default 
      secureJsonData:
        password: "default"
