{
 "title": "Solana Validator Dashboard",
 "description": "Solana Validator Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_epoch" }
   ]
  },
  {
   "title": "Epoch progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_pctEpochElapsed" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sol_status" }
   ]
  },
  {
   "title": "Leaderslots this epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_leaderSlots" }
   ]
  },
  {
   "title": "MIssed slots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_skippedSlots" }
   ]
  },
  {
   "title": "Skip rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_pctSkipped" }
   ]
  },
  {
   "title": "Active stake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_activatedStake" }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_nodes" }
   ]
  },
  {
   "title": "My Credits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sol_validatorCreditsCurrent", "legendFormat": "credits" }
   ]
  },
  {
   "title": "Skip rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sol_pctSkipped", "legendFormat": "My skip rate" },
    { "expr": "sol_pctTotSkipped", "legendFormat": "Cluster skip rate" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "RAM used "
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=~\"$job\"} / node_memory_SwapTotal_bytes{job=~\"$job\"})) * 100",
     "legendFormat": "SWAP used "
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk used"
    }
   ]
  }
 ]
}