global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          env: 'dev'

  - job_name: 'arbitrage'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          env: 'dev'

  - job_name: 'fcsc-agent'
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - 'targets/vm-health.yml'
        refresh_interval: 30s
  
  

  - job_name: fastcar2-node-exporter
    static_configs:
      - targets: ["10.77.251.1:9100"]
        labels:
          env: 'dev'
          source: 'node-exporter'

  - job_name: fastcar1-node-exporter
    static_configs:
      - targets: ["64.130.40.37:9100"]
        labels:
          env: 'prod'
          source: 'node-exporter'

  - job_name: 'fastcar1-solana-validator'
    scrape_interval: 5s
    static_configs:
      - targets: ['64.130.40.37:19100']
        labels:
          env: 'prod'
          source: 'solana-validator'

  - job_name: 'fastcar1-geyser'
    scrape_interval: 5s
    static_configs:
      - targets: ['64.130.40.37:19101']
        labels:
          env: 'prod'
          source: 'geyser'

  - job_name: 'fastcar1-jet'
    scrape_interval: 5s
    static_configs:
      - targets: ['64.130.40.37:19102']
        labels:
          env: 'prod'
          source: 'jet'

  - job_name: 'fastcar1-solana-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['64.130.40.37:19103']
        labels:
          env: 'prod'
          source: 'solana-exporter'

  - job_name: process-exporter
    static_configs:
      - targets: ["host.docker.internal:9256"]
        labels:
          env: 'dev'

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          env: 'dev'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - grafana:3000
